function setup(){
createCanvas(850,600);
input=createInput().attribute("placeholder", "Enter your name ")
input.position(350,250)
bP=createButton("SUBMIT")
bP.position(400,280)
bP.mousePressed(logic)



}
function draw(){
background("rgb(0,255,255)");

  
}
function logic(){
input.hide()
bP.hide()
H=createElement("h1")
H.html("Hello! "+input.value() )
H.position(410,10)
A=createElement("h1")
A.html("Let's see if you can answer this")
A.position(230,50)
B=createElement("h1")
B.html("Question1")
B.position(400,100)
C=createElement("h2")
C.html("Q1) Name the Planet having  maximum density.")
C.position(50,200)
D=createElement("h2")
D.html("a) Venus")
D.position(50,250)
E=createElement("h2")
E.html("b) Saturn")
E.position(50,300)
G=createElement("h2")
G.html("c) Mercury")
G.position(50,350)
I=createElement("h2")
I.html("d) Uranus")
I.position(50,400)
output=createInput().attribute("placeholder", "Enter the correct option")
output.position(50,550)   
bp=createButton("SUBMIT")
bp.position(600,550)
bp.mousePressed(logic2)
}
function logic2(){
H.hide()
A.hide()
B.hide()
C.hide()
D.hide()
E.hide()
G.hide()
I.hide()
bp.hide()
output.hide()
W=createElement("h1")
W.html("YOUR ANSWER")
W.position(100,100)
Q=createElement("h2")
Q.html("Q1) "+output.value())
Q.position(100,150)
S=createElement("h1")
S.html("CORRECT ANSWER")
S.position(100,300)
E=createElement("h2")
E.html("Q1) c)")
E.position(100,350)
next=createButton("Next")
next.position(650,450)
next.mousePressed(logic3)
}

function logic3(){
H.hide()
A.hide()
B.hide()
C.hide()
D.hide()
E.hide()
G.hide()
I.hide()
bp.hide()
output.hide()
W.hide()
Q.hide()
S.hide()
E.hide()
D.hide()
next.hide()
H=createElement("h1")
H.html("Hello! "+input.value() )
H.position(410,10)
A=createElement("h1")
A.html("Let's see if you can answer this")
A.position(230,50)
B=createElement("h1")
B.html("Question2")
B.position(400,100)
C=createElement("h2")
C.html("Q2) Name the planets having retrograde rotation")
C.position(50,200)
D=createElement("h2")
D.html("a) Mercury & Uranus")
D.position(50,250)
E=createElement("h2")
E.html("b) Venus & Saturn")
E.position(50,300)
G=createElement("h2")
G.html("c) Jupiter & Uranus")
G.position(50,350)
I=createElement("h2")
I.html("d) Venus & Uranus")
I.position(50,400)
output=createInput().attribute("placeholder", "Enter the correct option")
output.position(50,550)   
bp=createButton("SUBMIT")
bp.position(600,550)
bp.mousePressed(logic4)
}

function logic4(){
    H.hide()
    A.hide()
    B.hide()
    C.hide()
    D.hide()
    E.hide()
    G.hide()
    I.hide()
    bp.hide()
    output.hide()
    W=createElement("h1")
    W.html("YOUR ANSWER")
    W.position(100,100)
    Q=createElement("h2")
    Q.html("Q2) "+output.value())
    Q.position(100,150)
    S=createElement("h1")
    S.html("CORRECT ANSWER")
    S.position(100,300)
    E=createElement("h2")
    E.html("Q2) d)")
    E.position(100,350)
    next=createButton("Next")
    next.position(650,450)
    next.mousePressed(logic5)
   
    }
    function logic5(){
        H.hide()
A.hide()
B.hide()
C.hide()
D.hide()
E.hide()
G.hide()
I.hide()
bp.hide()
output.hide()
W.hide()
Q.hide()
S.hide()
E.hide()
D.hide()
next.hide()
        H=createElement("h1")
        H.html("Hello! "+input.value() )
        H.position(410,10)
        A=createElement("h1")
        A.html("Let's see if you can answer this")
        A.position(230,50)
        B=createElement("h1")
        B.html("Question3")
        B.position(400,100)
        C=createElement("h2")
        C.html("Q3)  Phobos and Deimos are the natural satellites of which planet?")
        C.position(50,200)
        D=createElement("h2")
        D.html("a) Venus")
        D.position(50,250)
        E=createElement("h2")
        E.html("b) Mars")
        E.position(50,300)
        G=createElement("h2")
        G.html("c) Jupiter")
        G.position(50,350)
        I=createElement("h2")
        I.html("d) Uranus")
        I.position(50,400)
        output=createInput().attribute("placeholder", "Enter the correct option")
        output.position(50,550)   
        bp=createButton("SUBMIT")
        bp.position(600,550)
        bp.mousePressed(logic6)
        }
        function logic6(){
        H.hide()
        A.hide()
        B.hide()
        C.hide()
        D.hide()
        E.hide()
        G.hide()
        I.hide()
        bp.hide()
        output.hide()
        W=createElement("h1")
        W.html("YOUR ANSWER")
        W.position(100,100)
        Q=createElement("h2")
        Q.html("Q3) "+output.value())
        Q.position(100,150)
        S=createElement("h1")
        S.html("CORRECT ANSWER")
        S.position(100,300)
        E=createElement("h2")
        E.html("Q3) b)")
        E.position(100,350)
        next=createButton("Next")
        next.position(650,450)
        next.mousePressed(logic7)
        }
        function logic7(){
            H.hide()
            A.hide()
            B.hide()
            C.hide()
            D.hide()
            E.hide()
            G.hide()
            I.hide()
            bp.hide()
            output.hide()
            W.hide()
            Q.hide()
            S.hide()
            E.hide()
            D.hide()
            next.hide()
            H=createElement("h1")
            H.html("Hello! "+input.value() )
            H.position(410,10)
            A=createElement("h1")
            A.html("Let's see if you can answer this")
            A.position(230,50)
            B=createElement("h1")
            B.html("Question4")
            B.position(400,100)
            C=createElement("h2")
            C.html("Q4) Ganymede, the biggest moon in our solar system, belongs to which planet?")
            C.position(50,200)
            D=createElement("h2")
            D.html("a) Jupiter")
            D.position(50,250)
            E=createElement("h2")
            E.html("b) Mars")
            E.position(50,300)
            G=createElement("h2")
            G.html("c) Saturn")
            G.position(50,350)
            I=createElement("h2")
            I.html("d) Uranus")
            I.position(50,400)
            output=createInput().attribute("placeholder", "Enter the correct option")
            output.position(50,550)   
            bp=createButton("SUBMIT")
            bp.position(600,550)
            bp.mousePressed(logic8)
            }
            function logic8(){
            H.hide()
            A.hide()
            B.hide()
            C.hide()
            D.hide()
            E.hide()
            G.hide()
            I.hide()
            bp.hide()
            output.hide()
            W=createElement("h1")
            W.html("YOUR ANSWER")
            W.position(100,100)
            Q=createElement("h2")
            Q.html("Q4) "+output.value())
            Q.position(100,150)
            S=createElement("h1")
            S.html("CORRECT ANSWER")
            S.position(100,300)
            E=createElement("h2")
            E.html("Q4) a)")
            E.position(100,350)
            next=createButton("Next")
            next.position(650,450)
            next.mousePressed(logic9)
            }
            function logic9(){
               H.hide()
A.hide()
B.hide()
C.hide()
D.hide()
E.hide()
G.hide()
I.hide()
bp.hide()
output.hide()
W.hide()
Q.hide()
S.hide()
E.hide()
D.hide()
next.hide()
                H=createElement("h1")
                H.html("Hello! "+input.value() )
                H.position(410,10)
                A=createElement("h1")
                A.html("Let's see if you can answer this")
                A.position(230,50)
                B=createElement("h1")
                B.html("Question5")
                B.position(400,100)
                C=createElement("h2")
                C.html("Q5) Planets which spin backwards relative to other planets of our solar system?")
                C.position(37,200)
                D=createElement("h2")
                D.html("a) Jupiter & Neptune")
                D.position(50,250)
                E=createElement("h2")
                E.html("b) Venus & Uranus")
                E.position(50,300)
                G=createElement("h2")
                G.html("c) Saturn & Mars")
                G.position(50,350)
                I=createElement("h2")
                I.html("d) Uranus & Mercury")
                I.position(50,400)
                output=createInput().attribute("placeholder", "Enter the correct option")
                output.position(50,550)   
                bp=createButton("SUBMIT")
                bp.position(600,550)
                bp.mousePressed(logic10)
                }
                function logic10(){
                H.hide()
                A.hide()
                B.hide()
                C.hide()
                D.hide()
                E.hide()
                G.hide()
                I.hide()
                bp.hide()
                output.hide()
                W=createElement("h1")
                W.html("YOUR ANSWER")
                W.position(100,100)
                Q=createElement("h2")
                Q.html("Q5) "+output.value())
                Q.position(100,150)
                S=createElement("h1")
                S.html("CORRECT ANSWER")
                S.position(100,300)
                E=createElement("h2")
                E.html("Q5) b)")
                E.position(100,350)
                D=createElement("h1")
                D.html("THANK YOU FOR ATTENDING OUR QUIZ!!😊😊")
                D.position(50,500)
                }
        
        

